Repository flekschas/piling.js, pull requests merged in 2020-01, with the labels that each got.

#45 Export import state
  DOCS.md
  examples/index.html
  examples/index.js
  src/library.js
  src/store.js
  src/utils.js
Labels: new feature

#54 Added PR and issue templates
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: dev

#52 Public event API
  CHANGELOG.md
  DOCS.md
  examples/lines.js
  src/library.js
  src/pile.js
  src/store.js
Labels: new feature

#57 Avoid line breaks
  examples/index.html
Labels: improvement

#51 Update grid system
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
  DOCS.md
  examples/index.html
  examples/index.js
  examples/lines.js
  examples/matrices.js
  examples/photos.js
  src/grid.js
  src/library.js
  src/pile.js
  src/store.js
Labels: improvement

#62 Allow piles cell align differently
  CHANGELOG.md
  DOCS.md
  examples/matrices.js
  examples/photos.js
  src/library.js
  src/pile.js
  src/store.js
Labels: new feature

#58 Flekschas/align by grid
  .github/ISSUE_TEMPLATE.md
  CHANGELOG.md
  DOCS.md
  examples/index.html
  package-lock.json
  package.json
  src/grid.js
  src/library.js
  src/pile.js
  src/utils.js
Labels: new feature

#67 Flekschas/refactor clean grid
  .github/ISSUE_TEMPLATE.md
  CHANGELOG.md
  examples/matrices.js
  examples/photos.js
  src/grid.js
  src/library.js
  src/store.js
  src/utils.js
Labels: improvement

#56 Style items and piles dynamically
  CHANGELOG.md
  DEV_DOCS.md
  DOCS.md
  examples/lines.js
  examples/matrices.js
  examples/photos.js
  src/item.js
  src/library.js
  src/pile.js
  src/preview.js
  src/store.js
  src/utils.js
Labels: new feature

#76 Flekschas/rename properties
  CHANGELOG.md
  DOCS.md
  examples/index.js
  examples/lines.js
  examples/photos.js
  src/grid.js
  src/library.js
  src/pile.js
  src/store.js
Labels: improvement

#80 Animate item rotation
  CHANGELOG.md
  DOCS.md
  examples/photos.js
  src/item.js
  src/library.js
  src/pile.js
  src/store.js
Labels: improvement

#81 Refactor scale pile
  CHANGELOG.md
  DOCS.md
  examples/matrices.js
  src/library.js
  src/pile.js
  src/store.js
  src/tweener.js
Labels: bug

#82 Update grid lines when updating grid
  CHANGELOG.md
  src/context-menu.js
  src/library.js
Labels: bug

#83 Restructure pile scene graph
  CHANGELOG.md
  DEV_DOCS.md
  src/library.js
  src/pile.js
Labels: improvement
