Repository flekschas/piling.js, pull requests merged in 2020-02, with the labels that each got.

#89 Add pile base scale
  CHANGELOG.md
  DOCS.md
  src/context-menu.js
  src/library.js
  src/pile.js
  src/store.js
Labels: bug

#86 Data-driven 1D and 2D layout arrangments
  .travis.yml
  CHANGELOG.md
  DOCS.md
  examples/index.js
  package-lock.json
  package.json
  rollup.config.js
  src/bounding-box.js
  src/defaults.js
  src/grid.js
  src/image-with-background.js
  src/image.js
  src/item.js
  src/library.js
  src/matrix-cover-aggregator.js
  src/matrix-preview-aggregator.js
  src/pile-item.js
  src/pile.js
  src/store.js
  src/tweener.js
  src/utils.js
  src/with-animated-property.js
  src/with-constructor.js
  src/with-property.js
  src/with-read-only-property.js
  src/with-size.js
Labels: new feature

#95 Flekschas/pile item style - color filters
  CHANGELOG.md
  DOCS.md
  src/defaults.js
  src/image-with-background.js
  src/image.js
  src/library.js
  src/store.js
  src/with-color-filters.js
Labels: new feature

#96 Draw border after position
  examples/matrices.js
  src/library.js
  src/pile.js
  src/store.js
Labels: bug

#99 Flekschas/animate drop merge with previews
  CHANGELOG.md
  src/library.js
Labels: improvement

#98 Flekschas/mouse only lasso
  CHANGELOG.md
  DOCS.md
  examples/matrices.js
  examples/photos.js
  package-lock.json
  package.json
  src/defaults.js
  src/lasso.js
  src/library.js
  src/store.js
Labels: new feature

#102 Eeeeenchanted/arrange by once
  CHANGELOG.md
  DOCS.md
  src/library.js
  src/store.js
Labels: bug

#97 Separate pile and preview bg color
  CHANGELOG.md
  DOCS.md
  src/defaults.js
  src/library.js
  src/pile.js
  src/store.js
Labels: bug

#101 Flekschas/umap
  DOCS.md
  examples/matrices.js
  package-lock.json
  package.json
  rollup.config.js
  src/defaults.js
  src/dimensionality-reducer.js
  src/lasso.js
  src/library.js
  src/pile.js
  src/popup.js
  src/spinner.js
  src/store.js
  src/umap-worker.js
  src/umap.js
  webpack.config.js
Labels: new feature

#103 Google quickdraw example
  examples/drawings.js
  examples/index.html
  examples/index.js
  examples/lines.js
  package-lock.json
  package.json
  src/aggregator.js
  src/index.js
  src/library.js
  src/pile.js
  src/quickdraw-cover-aggregator-worker.js
  src/quickdraw-cover-aggregator.js
  src/quickdraw-cover-renderer.js
  src/quickdraw-renderer.js
  src/renderer.js
  src/store.js
Labels: examples

#108 Flekschas/vector-property-support
  DOCS.md
  examples/matrices.js
  package-lock.json
  package.json
  src/library.js
Labels: improvement

#106 Texture update
  examples/drawings.js
  examples/index.html
  examples/index.js
  examples/lines.js
  examples/matrices.js
  examples/photos.js
  src/image-with-background.js
  src/image.js
  src/item.js
  src/library.js
  src/pile-item.js
  src/pile.js
  src/store.js
  src/svg-renderer.js
  src/with-destroy.js
  src/with-scale.js
Labels: improvement

#110 Flekschas/joy plot
  CHANGELOG.md
  examples/index.html
  examples/index.js
  examples/joy-plot.js
  package-lock.json
  package.json
  src/bounding-box.js
  src/pile.js
  src/svg-renderer.js
  src/with-color-filters.js
Labels: bug, examples

#112 Flekschas/levels
  examples/lines.js
  package-lock.json
  package.json
  src/animator.js
  src/context-menu.js
  src/grid.js
  src/levels.js
  src/library.js
  src/pile.js
  src/store.js
  src/stylesheet.js
Labels: new feature

#113 pileItemAlignment -> pileItemOffset
  CHANGELOG.md
  DOCS.md
  examples/drawings.js
  examples/joy-plot.js
  examples/lines.js
  examples/photos.js
  src/library.js
  src/pile.js
  src/store.js
Labels: improvement

#109 Flekschas/microscopy vitessce example
  CHANGELOG.md
  DOCS.md
  examples/index.html
  examples/index.js
  examples/index.scss
  examples/styles/checkbox.scss
  examples/styles/colors.scss
  examples/styles/input-range.scss
  examples/styles/radio.scss
  examples/styles/transitions.scss
  examples/vitessce-data-fetcher.js
  examples/vitessce-renderer.js
  examples/vitessce-utils.js
  examples/vitessce.fs
  examples/vitessce.js
  examples/vitessce.vs
  package-lock.json
  package.json
  src/defaults.js
  src/image-with-background.js
  src/image.js
  src/lasso.js
  src/levels.js
  src/library.js
  src/popup.js
  src/spinner.js
  src/store.js
  src/utils.js
  src/with-scale.js
  src/with-size.js
  webpack.config.js
Labels: bug, examples
