Repository flekschas/piling.js, pull requests merged in 2020-03, with the labels that each got.

#121 Remove items on a pile
  examples/lines.js
  src/library.js
  src/pile.js
  src/store.js
Labels: improvement

#127 Flekschas/representative cover
  CHANGELOG.md
  DOCS.md
  examples/drawings.js
  examples/google-quickdraw-cover-aggregator-worker.js
  examples/google-quickdraw-cover-aggregator.js
  examples/google-quickdraw-cover-renderer.js
  examples/google-quickdraw-renderer.js
  examples/matrices.js
  examples/vitessce.js
  package-lock.json
  package.json
  src/aggregator.js
  src/image-with-background.js
  src/image.js
  src/index.js
  src/library.js
  src/matrix-cover-aggregator-worker.js
  src/matrix-cover-aggregator.js
  src/matrix-preview-aggregator.js
  src/quickdraw-cover-renderer.js
  src/renderer.js
  src/representative-aggregator-worker.js
  src/representative-aggregator.js
  src/representative-renderer.js
  src/store.js
  webpack.config.js
Labels: new feature

#100 Scatterplot example
  CHANGELOG.md
  DOCS.md
  examples/index.html
  examples/index.js
  examples/matrices.js
  examples/scatterplot-cover-aggregator.js
  examples/scatterplot-preview-aggregator.js
  examples/scatterplot-preview-renderer.js
  examples/scatterplot-renderer.js
  examples/scatterplots.js
  package-lock.json
  package.json
  src/library.js
  src/pile.js
  src/popup.js
  src/store.js
Labels: examples

#132 Add placeholder
  src/pile.js
Labels: improvement

#130 Time series
  .gitignore
  DOCS.md
  examples/environment.yml
  examples/index.html
  examples/index.js
  examples/index.scss
  examples/movie-frames-embedding.ipynb
  examples/time-series.js
  examples/vitessce.js
  src/defaults.js
  src/library.js
  src/pile.js
  src/representative-renderer.js
  src/store.js
Labels: examples

#144 Split all
  CHANGELOG.md
  DOCS.md
  examples/lines.js
  src/library.js
Labels: new feature

#136 Cell size
  CHANGELOG.md
  DOCS.md
  examples/drawings.js
  examples/index.js
  examples/matrices.js
  examples/photos.js
  examples/time-series.js
  examples/vitessce.js
  src/grid.js
  src/library.js
  src/store.js
Labels: improvement

#148 Flekschas/preview scaling
  CHANGELOG.md
  DOCS.md
  examples/matrices.js
  src/image-with-background.js
  src/library.js
  src/pile-item.js
  src/pile.js
  src/store.js
  src/with-scale.js
Labels: new feature

#133 Pile label
  CHANGELOG.md
  DOCS.md
  examples/drawings.js
  examples/scatterplots.js
  src/defaults.js
  src/library.js
  src/pile.js
  src/store.js
  src/tweener.js
Labels: new feature

#151 Pile background color
  CHANGELOG.md
  DOCS.md
  examples/drawings.js
  examples/joy-plot.js
  examples/lines.js
  src/library.js
  src/pile.js
  src/store.js
Labels: improvement

#153 Flekschas/hide pixi from renderer
  examples/google-quickdraw-renderer.js
  src/image-renderer.js
  src/image-with-background.js
  src/image.js
  src/representative-renderer.js
  src/svg-renderer.js
  src/utils/index.js
  src/utils/is-ndarray.js
  src/utils/to-display-object.js
Labels: improvement

#159 Flekschas/docsify
  DEV_DOCS.md
  README.md
  copy-example-data.sh
  docs/.nojekyll
  docs/CHANGELOG.md
  docs/README.md
  docs/_sidebar.md
  docs/index.html
  docs/material-ocean.css
  package.json
Labels: documentation

#157 Update layout related issues
  src/grid.js
  src/library.js
  src/pile.js
Labels: bug

#138 Flekschas/show pile size number
  CHANGELOG.md
  docs/README.md
  examples/lines.js
  package-lock.json
  package.json
  src/badge-factory.js
  src/badge.js
  src/defaults.js
  src/image.js
  src/library.js
  src/pile.js
  src/popup.js
  src/rounded-rectangle-factory.js
  src/store.js
  src/utils/index.js
  src/utils/to-alignment.js
  src/with-clone.js
Labels: new feature

#158 Expand sidebar
  CHANGELOG.md
  examples/index.js
  src/library.js
  src/pile.js
  src/store.js
Labels: improvement

#161 Flekschas/rename and improve pile by
  docs/README.md
  examples/index.js
  src/library.js
  src/store.js
Labels: improvement

#167 Pile label size aggregator
  CHANGELOG.md
  docs/README.md
  examples/drawings.js
  examples/index.js
  src/library.js
  src/pile.js
  src/store.js
Labels: improvement

#172 Switch between drawing categories
  examples/drawings.js
  src/library.js
  src/store.js
Labels: examples

#177 Update cover
  CHANGELOG.md
  examples/drawings.js
  src/library.js
  src/pile.js
Labels: bug

#174 Functional properties
  CHANGELOG.md
  docs/README.md
  src/library.js
  src/pile.js
  src/utils/get-item-prop.js
  src/utils/get-pile-prop.js
  src/utils/index.js
Labels: improvement
